### ISSUE TITLE
Outdated InfluxDB Causing Unnecessary Load

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/sensors.AFRICA-AQ-map#5]
> Hi Chege, do you know who is responsible for http://map.aq.sensors.africa/ ? The version of our map used there is an old version. And it uses our InfluxDB for the graphs, but your sensors aren’t available there. So the map creates a load that is unnecessary.

**Comment by DavidLemayian** [comment]
Could be solved by - https://github.com/CodeForAfricaLabs/sensors.AFRICA-AQ-map/pull/3
